# Generated by Django 5.1.1 on 2024-10-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='car_color',
            field=models.CharField(default='', max_length=30),
        ),
    ]
